services:
 mysql:
  image: mysql:latest
  container_name: mysql
  restart: always
  volumes:
    - mysql-volume:/var/lib/mysql
    - ./docker-assets/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./mysql-backups:/backups
  environment:
    MYSQL_ROOT_PASSWORD: ${ROOT_PASS:?error}
    MYSQL_DATABASE: ${CONNECTED_DB:?error}
    MYSQL_USER: ${DB_USER:?error}
    MYSQL_PASSWORD: ${USER_PASS:?error}
  networks:
      - app-network

 nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker-assets/nginx/sites-enabled/nginx.conf:/etc/nginx/conf.d/default.conf
    stdin_open: true
    tty: true
    networks:
      - app-network

 ghost:
  image: ghost:5-alpine
  container_name: ghost
  volumes:
    - ./docker-assets/ghost_content:/var/lib/ghost/content
  restart: always
  ports:
    - 2368:2368
  environment:
    database__client: mysql
    database__connection__host: mysql
    database__connection__user: ${DB_USER:?error}
    database__connection__password: ${USER_PASS:?error}
    database__connection__database: ${CONNECTED_DB:?error}
    url: ${CONNECTED_DB:?error}

  networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-volume:
  ghost-volume:
